In [1]:
#Step 1: Importing the Libraries


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
#Step 2: Importing the dataset


dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')


In [3]:
#Step 3:Describe dataset,See dimention and Exlpore dataset


dataset.describe()


sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [4]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
dataset.shape

(150, 5)

In [6]:
X = dataset.iloc[:,:4].values

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y = dataset['species'].values
y


array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)


In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train


array([[-4.96192597e-01, -1.16703931e-01,  4.47297469e-01,
         4.06991302e-01],
       [ 1.27241468e+00,  1.09174645e-01,  7.84526975e-01,
         1.43517985e+00],
       [ 1.27241468e+00,  3.35053222e-01,  1.12175648e+00,
         1.43517985e+00],
       [-1.42471142e-01, -3.42582507e-01,  2.78682716e-01,
         1.49944164e-01],
       [-2.60378293e-01, -1.24609681e+00,  1.10067964e-01,
        -1.07102974e-01],
       [-4.96192597e-01,  1.46444610e+00, -1.23885006e+00,
        -1.26381510e+00],
       [ 2.11250313e-01, -3.42582507e-01,  4.47297469e-01,
         4.06991302e-01],
       [-9.67821203e-01, -1.69785397e+00, -2.27161542e-01,
        -2.35626543e-01],
       [-9.67821203e-01,  1.01268895e+00, -1.18264514e+00,
        -7.49720819e-01],
       [-9.67821203e-01, -2.37548969e+00, -1.14751707e-01,
        -2.35626543e-01],
       [-1.67526411e+00,  3.35053222e-01, -1.35125989e+00,
        -1.26381510e+00],
       [-1.08572836e+00,  1.09174645e-01, -1.23885006e+00,
      

In [11]:
X_test

array([[-0.14247114, -0.11670393,  0.27868272,  0.02142059],
       [ 1.62613613,  0.33505322,  1.29037123,  0.79256201],
       [ 0.32915747, -0.34258251,  0.5597073 ,  0.27846773],
       [ 0.68287892, -0.56846108,  1.06555156,  1.17813272],
       [ 0.56497177, -0.56846108,  0.78452698,  0.4069913 ],
       [-0.26037829, -0.11670393,  0.44729747,  0.4069913 ],
       [-0.14247114, -0.56846108,  0.2224778 ,  0.14994416],
       [-1.43944981,  1.23856753, -1.51987465, -1.2638151 ],
       [-1.79317127, -0.11670393, -1.46366973, -1.39233866],
       [ 0.21125031,  0.78681037,  0.44729747,  0.53551487],
       [ 1.39032183,  0.33505322,  0.5597073 ,  0.27846773],
       [ 0.44706462,  0.78681037,  0.95314173,  1.43517985],
       [ 0.68287892, -0.79433966,  0.89693681,  0.92108558],
       [ 0.68287892, -0.34258251,  0.33488763,  0.14994416],
       [-0.26037829, -0.56846108,  0.67211714,  1.04960915],
       [ 1.03660038, -1.24609681,  1.1779614 ,  0.79256201],
       [-1.32154266,  0.

In [12]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)


GaussianNB()

In [13]:
#Step 6: Predicting the Test set results
y_pred = classifier.predict(X_test) 
y_pred


array(['versicolor', 'virginica', 'versicolor', 'virginica', 'versicolor',
       'versicolor', 'versicolor', 'setosa', 'setosa', 'versicolor',
       'versicolor', 'virginica', 'virginica', 'versicolor', 'virginica',
       'virginica', 'setosa', 'versicolor', 'setosa', 'setosa',
       'versicolor', 'virginica', 'versicolor', 'setosa', 'versicolor',
       'setosa', 'versicolor', 'setosa', 'virginica', 'virginica'],
      dtype='<U10')

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


array([[ 8,  0,  0],
       [ 0, 11,  0],
       [ 0,  2,  9]], dtype=int64)

In [15]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))


Accuracy :  0.9333333333333333


In [16]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df


Real Values Predicted Values
0   versicolor       versicolor
1    virginica        virginica
2   versicolor       versicolor
3    virginica        virginica
4    virginica       versicolor
5   versicolor       versicolor
6   versicolor       versicolor
7       setosa           setosa
8       setosa           setosa
9   versicolor       versicolor
10  versicolor       versicolor
11   virginica        virginica
12   virginica        virginica
13  versicolor       versicolor
14   virginica        virginica
15   virginica        virginica
16      setosa           setosa
17  versicolor       versicolor
18      setosa           setosa
19      setosa           setosa
20   virginica       versicolor
21   virginica        virginica
22  versicolor       versicolor
23      setosa           setosa
24  versicolor       versicolor
25      setosa           setosa
26  versicolor       versicolor
27      setosa           setosa
28   virginica        virginica
29   virginica        virginica